import { useEffect,useState } from 'react';
import axios from 'axios';
import { BrowserRouter,Routes,Route,Link,Navigate,useNavigate } from 'react-router-dom';
import './styles.css';
const api=axios.create({baseURL:import.meta.env.VITE_API_URL||'http://localhost:4000'});api.interceptors.request.use(c=>{const t=localStorage.getItem('token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});
function Login(){const [email,setEmail]=useState('admin@erp.local'),[password,setPassword]=useState('Password123!'),[error,setError]=useState('');const nav=useNavigate();async function submit(e:any){e.preventDefault();try{const r=await api.post('/auth/login',{email,password});localStorage.setItem('token',r.data.token);localStorage.setItem('user',JSON.stringify(r.data.user));nav('/');}catch(e:any){setError(e.response?.data?.message||'Login failed')}}return <div className="login"><form onSubmit={submit}><h1>ERP CRM</h1><p>Operations Portal</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password"/><button>Sign in</button>{error&&<small>{error}</small>}<div className="hint">Demo: admin@erp.local / Password123!</div></form></div>}
function Shell(){const user=JSON.parse(localStorage.getItem('user')||'null');const nav=useNavigate();if(!user)return <Navigate to="/login"/>;const logout=()=>{localStorage.clear();nav('/login')};return <div className="shell"><aside><h2>ERP CRM</h2><span className="role">{user.role}</span><nav><Link to="/">Dashboard</Link><Link to="/customers">Customers</Link><Link to="/products">Products</Link><Link to="/challans">Challans</Link></nav><button onClick={logout}>Logout</button></aside><main><Routes><Route path="/" element={<Dashboard user={user}/>}/><Route path="/customers" element={<Customers/>}/><Route path="/products" element={<Products/>}/><Route path="/challans" element={<Challans/>}/></Routes></main></div>}
function Dashboard({user}:any){return <><header><h1>Dashboard</h1><p>Welcome, {user.name}</p></header><div className="cards"><div><b>Customers</b><span>CRM management</span></div><div><b>Products</b><span>Inventory tracking</span></div><div><b>Challans</b><span>Sales operations</span></div><div><b>Role</b><span>{user.role}</span></div></div></>}
function Customers(){const [data,setData]=useState<any[]>([]);useEffect(()=>{api.get('/customers').then(r=>setData(r.data.data))},[]);return <><header><h1>Customers</h1><p>Customer CRM</p></header><section className="panel"><table><thead><tr><th>Name</th><th>Business</th><th>Mobile</th><th>Status</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{x.customerName}</td><td>{x.businessName}</td><td>{x.mobile}</td><td>{x.status}</td></tr>)}</tbody></table></section></>}
function Products(){const [data,setData]=useState<any[]>([]);useEffect(()=>{api.get('/products').then(r=>setData(r.data.data))},[]);return <><header><h1>Products & Inventory</h1><p>Stock overview</p></header><section className="panel"><table><thead><tr><th>SKU</th><th>Product</th><th>Category</th><th>Stock</th><th>Minimum</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{x.sku}</td><td>{x.name}</td><td>{x.category}</td><td>{x.currentStock}</td><td>{x.minimumStock}</td></tr>)}</tbody></table></section></>}
function Challans(){const [data,setData]=useState<any[]>([]);useEffect(()=>{api.get('/challans').then(r=>setData(r.data.data))},[]);return <><header><h1>Sales Challans</h1><p>Draft and confirmed sales documents</p></header><section className="panel"><table><thead><tr><th>Number</th><th>Customer</th><th>Quantity</th><th>Status</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{x.challanNumber}</td><td>{x.customer?.customerName}</td><td>{x.totalQuantity}</td><td>{x.status}</td></tr>)}</tbody></table></section></>}
function App(){return <BrowserRouter><Routes><Route path="/login" element={<Login/>}/><Route path="/*" element={<Shell/>}/></Routes></BrowserRouter>}export default App;
